### ISSUE TITLE
Cannot find module `commander`

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/tubeify#4]
Running
`node cli.js -j tests/test.json -b 25 -l 1000 -t -1`
I get

```
[heumos@wave tubeify]$ node cli.js -j tests/test.json -b 25 -l 1000 -t -1
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/heumos/git/tubeify/cli.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by subwaystation** [comment]
`npm install -g commander` does not solve this issue. Any ideas?

**Comment by subwaystation** [comment]
`[heumos@wave tubeify]$ node --version
v10.16.3`

**Comment by subwaystation** [comment]
Updating the node version `[heumos@wave tubeify]$ node --version
v12.0.0` did not help.

**Comment by subwaystation** [comment]
Do you have any ideas @6br ?
@josiahseaman How did you get it to run?

**Comment by subwaystation** [comment]
`npm install` solved this issue. We need to update the README.
