### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/tubeify#5]
Now I run into the following problem:
```
[heumos@wave tubeify]$ node cli.js -j tests/test.json -b 25 -l 1000 -t -1
undefined:1
[
 

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at func (/home/heumos/git/tubeify_master/tubeify/cli.js:65:27)
    at ReadStream.<anonymous> (/home/heumos/git/tubeify_master/tubeify/cli.js:43:9)
    at ReadStream.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at ReadStream.Readable.push (_stream_readable.js:223:10)
    at internal/fs/streams.js:191:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:481:5)
```
Either the input JSON is malformed or the line by line parser has problems when the input is only `[`.
I suspect the last one as `[` is not a valid JSON. 
Is this `csv2json`'s fault?

**Comment by 6br** [comment]
I confirmed the issue. I will fix it soon.
